-- Create users table (updated schema)
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY, -- Unique user ID
    username VARCHAR(50) NOT NULL UNIQUE, -- Login username
    email VARCHAR(100) NOT NULL UNIQUE,   -- User email
    password_hash VARCHAR(255) NOT NULL,  -- Bcrypt password hash
    role ENUM('admin', 'staff') NOT NULL DEFAULT 'staff', -- User role
    status ENUM('active', 'inactive') NOT NULL DEFAULT 'active', -- Account status
    last_login DATETIME DEFAULT NULL,     -- Last login timestamp
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- Account creation time
);

-- Create products table (updated schema)
CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY, -- Product ID
    supplier_id INT DEFAULT NULL,      -- FK to suppliers (if you add a suppliers table)
    name VARCHAR(100) NOT NULL,        -- Product name
    description TEXT,                  -- Product description
    image VARCHAR(255),                -- Image file path or URL
    price DECIMAL(10,2) NOT NULL,      -- Product price
    quantity_in_stock INT NOT NULL DEFAULT 0, -- Current stock
    low_stock_threshold INT NOT NULL DEFAULT 0, -- Low stock warning threshold
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create sales table
CREATE TABLE IF NOT EXISTS sales (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_id INT NOT NULL,
    qty INT NOT NULL,
    total DECIMAL(10,2) NOT NULL,
    sold_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sold_by INT NOT NULL,
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (sold_by) REFERENCES users(id)
);

-- Insert initial admin user (update hash for production)
-- Password: admin123 (bcrypt hash)
INSERT INTO users (username, email, password_hash, role, status, last_login) VALUES (
  'admin',
  'admin@example.com',
  '$2y$10$u1QwQwQwQwQwQwQwQwQwQeQwQwQwQwQwQwQwQwQwQwQwQwQwQwQw',
  'admin',
  'active',
  NULL
);
-- Note: Replace the password_hash with a real bcrypt hash for 'admin123' generated by PHP 

INSERT INTO products (supplier_id, name, description, image, price, quantity_in_stock, low_stock_threshold)
VALUES
  (1, 'Premium Jasmine Rice', 'High quality jasmine rice.', 'jasmine.jpg', 50.00, 100, 10),
  (2, 'Brown Rice', 'Nutritious brown rice.', 'brown.jpg', 45.00, 80, 8),
  (1, 'Sticky Rice', 'Perfect for desserts.', 'sticky.jpg', 60.00, 50, 5); 

CREATE TABLE IF NOT EXISTS product (
    product_id INT AUTO_INCREMENT PRIMARY KEY,
    supplier_id INT,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL,
    quantity_in_stock INT NOT NULL DEFAULT 0,
    low_stock_threshold INT NOT NULL DEFAULT 0,
    image VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (supplier_id) REFERENCES supplier(supplier_id)
);

CREATE TABLE IF NOT EXISTS inventorylog (
    log_id INT AUTO_INCREMENT PRIMARY KEY,
    product_id INT NOT NULL,
    user_id INT NOT NULL,
    change_type ENUM('add', 'remove', 'adjust') NOT NULL,
    log_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    quantity_change INT NOT NULL,
    FOREIGN KEY (product_id) REFERENCES product(product_id),
    FOREIGN KEY (user_id) REFERENCES user(user_id)
); 

CREATE TABLE IF NOT EXISTS supplier (
    supplier_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    contact VARCHAR(100),
    phone VARCHAR(30),
    email VARCHAR(100),
    address VARCHAR(255)
); 